### ISSUE TITLE
Deploy the dashboard on DDSC website

### ISSUE THREAD

**Issue by saattrupdan** [Dansk-Data-Science-Community/danish-data-science-salary-survey#23]
The dashboard needs to be deployed on [the website](https://ddsc.io/) in a safe and stable way.

**Comment by IIMunchII** [comment]
@saattrupdan we should have a discussion on online meeting to figure out how we host the applikation on our domain. We need to consider a few things. First. We cannot deploy the application on some cloud service and expect it to also be accessable through some path on ddsc.io/salary/dashboard for instance. This is due to the fact that the cloud servers are not allowed on our domain for obvious reasons.

What we instead could do is link to some other domain from ddsc.io, but the question becomes, is that what we want? If we where to host the application ourselves we could do so by simply placing it behind an Nginx proxy. Let me know what you guys think about this, cause then I could start trying that out on staging.ddsc.io for you to test etc.

**Comment by saattrupdan** [comment]
@IIMunchII Let's discuss it later. I don't have time these days to work on it, but there's so rush either. Let's discuss this in a week or two 🙂

**Comment by saattrupdan** [comment]
Now live at https://ddsc.io/members/salary !
